# Generated by Django 3.0.4 on 2020-03-20 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('production_year', models.IntegerField()),
                ('price', models.IntegerField()),
                ('mark', models.CharField(max_length=30)),
                ('owner_name', models.CharField(max_length=30)),
                ('hp', models.IntegerField()),
                ('number_of_doors', models.IntegerField()),
            ],
        ),
    ]
