# Generated by Django 3.0.4 on 2020-04-01 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('from_adress', models.CharField(max_length=30)),
                ('out_time', models.DateTimeField(verbose_name='out time')),
                ('to_adress', models.CharField(max_length=30)),
                ('porpose', models.CharField(max_length=50)),
                ('back_time', models.DateTimeField(verbose_name='return time')),
            ],
        ),
    ]
