# Generated by Django 3.0.4 on 2020-04-13 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
