# Generated by Django 3.0.4 on 2020-03-31 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albums',
            name='release_year',
            field=models.DateField(verbose_name='date released'),
        ),
        migrations.AlterField(
            model_name='songs',
            name='favorite',
            field=models.IntegerField(default=0),
        ),
    ]
