# Generated by Django 3.0.4 on 2020-04-04 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Person', '0003_auto_20200404_1949'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='image',
            new_name='profile_pic',
        ),
    ]
