# Generated by Django 3.0.4 on 2020-09-25 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avto',
            name='year',
            field=models.IntegerField(),
        ),
    ]
